### ISSUE TITLE
如何驱动移动版 HD4600 ?

### ISSUE THREAD

**Issue by pinocchio2mx** [ZzMark/Thinkpad-E440-Hackintosh#12]
你好，我的笔记本型号是 ThinkPad E440 20C5A08KCD ，CPU i7-4712MQ， 显卡 HD4600 ，有几个问题想请教你。

都说驱动 HD4600 要仿冒 0x04128086 , 但是不管使用哪种方法，只要我一仿冒 04128086 必定进不了系统，屏幕显示 kextd stall IGPU 或者 busy timeout IGPU 。

你有没有遇见过这个错误，你驱动 HD4600 除了给 DSDT 和 SSDT 打补丁还有没有改别的地方？打补丁的过程有没有需要特别注意的地方？

另外我的 CPU 架构也没有被识别，显示为 an unknown CPU model  ，你遇见过这个问题吗？

**Comment by zzmark** [comment]
cpu那个问题可以检查下机型，我选择的是 macbook pro 11.1

显卡出现kextd stall igpu 和 busy timeout igpu 的话，检查自己是不是多加了kext

hd4600也不是每个人都该仿冒这个id，不过笔记本的话应该都差不多，我现在是4700mq还是用这个id
不过现在有个好东西，叫 whaterergreen，10.14的话可以考虑下这东西

我的10.14研究目前还没有结束，声卡没有搞定，近几天我会把不完善的版本发布到dev分支上

**Comment by pinocchio2mx** [comment]
感谢回复，前两天刚搞定，是我 BIOS 的问题。我之前的 BIOS 是一个亮机很慢的问题 BIOS ，因为 Windows 运行一切正常，再加上嫌刷 BIOS 麻烦，所以一直没有在意。走了很多弯路后决定尝试刷新BIOS，刷了一个正常的BIOS后用 Whateverevergreen 很顺利地就驱动核显了，CPU也认了。

声卡注入ID就能驱动啊，我也是10.14

**Comment by zzmark** [comment]
声卡注入id用applealc就能驱动，这是不出意外的情况。现在是出了问题，谁都找不到声卡在哪，applealc只能找到核显上的hdmi audio，所以还是有些问题。
这阵子人在外边一直没回去，等回去再更新文档。
最近盯上了 opencore，整好也试试新东西
