### ISSUE TITLE
CONEXANT CX20751/2 Audio (not work to use AppleALC)

### ISSUE THREAD

**Issue by zzmark** [ZzMark/Thinkpad-E440-Hackintosh#13]
CONEXANT CX20751/2 Audio (not work to use AppleALC)

使用 lilu + appleALC，无法识别到设备

**Comment by sudoyang** [comment]
E540 同样问题

**Comment by zzmark** [comment]
我这里是声卡挂掉了，你检查一下 lilu 的日志，看看有没有识别到设备

**Comment by sudoyang** [comment]
我回头查一下， 不过多半不是硬件问题。我是升级了最新的mac os，前一个版本声音还没问题。

**Comment by sudoyang** [comment]
我follow这个帖子，成功解决问题了，是版本不统一，你可以试一下。
https://www.tonymacx86.com/threads/lilu-and-whatevergreen-kexts-not-loading-properly.268405/

**Comment by zzmark** [comment]
那就恭喜了，我没必要尝试因为我声卡在win都不认了

**Comment by LunaticTian** [comment]
建议可以增加该音频驱动，由使用者测试。
