### ISSUE TITLE
WIFI

### ISSUE THREAD

**Issue by coderhss** [ZzMark/Thinkpad-E440-Hackintosh#14]
可以使用USB拓展的无线网卡么

**Comment by zzmark** [comment]
抱歉年假前后没有回复
可以使用，我用过的方案有360wifi，水星的150m，华为的4g随身wifi，前两者需要自行寻找驱动，后者自带了驱动

但要注意，360wifi和水星的150m，我手上这两个，前者是联发科方案，后者是螃蟹方案，后者比前者稳定些，前者驱动更多，不同版本性能不一致，不是太推荐用联发科方案，需要大量精力去测试稳定性

像是天生就支持mac的usb方案，可以随便使用，不用操心稳定性，不过操作都没有系统内置方便。

可供参考

**Comment by ZzMark** [comment]
抱歉年假前后没有回复
可以使用，我用过的方案有360wifi，水星的150m，华为的4g随身wifi，前两者需要自行寻找驱动，后者自带了驱动

但要注意，360wifi和水星的150m，我手上这两个，前者是联发科方案，后者是螃蟹方案，后者比前者稳定些，前者驱动更多，不同版本性能不一致，不是太推荐用联发科方案，需要大量精力去测试稳定性

像是天生就支持mac的usb方案，可以随便使用，不用操心稳定性，不过操作都没有系统内置方便。

可供参考
