### ISSUE TITLE
Clover启动速度慢？

### ISSUE THREAD

**Issue by youshupp** [ZzMark/Thinkpad-E440-Hackintosh#5]
首先非常感谢，系统目前运行很完美，唯一遇到的问题是启动速度和patch dsdt之前相比慢了很多，是存在这个问题的吗？还是因为个别机器的问题？

**Comment by youshupp** [comment]
http://imgur.com/a/U5HSM
这是启动时候的情况，在这上面停留了超过至少一分钟，然后才跳过正常启动，是什么原因？

**Comment by zzmark** [comment]
看这个图，你的设备和我有些区别，我的dsdt表不能很精确的对应你的设备，试试移除dsdt开机速度能不能正常，如果正常了的话，你需要自己提取dsdt，自己制作一套dsdt文件，

**Comment by youshupp** [comment]
嗯，没错，移除了以后的确是正常了。我看了你修改的readme，看上去有hdmi的改动，那部分具体是怎么样的呢？

**Comment by youshupp** [comment]
嗯，的确是这个问题。我自己修改过后已经正常了，就是现在键盘快捷按键还不能用，别的问题暂时没有发现

**Comment by zzmark** [comment]
快捷键你是说那几个功能键像是大写锁定之类的不能用，还是上面那一排东西不能用，大写锁定之类的你就去更新VoodooPS2这个驱动，到Rehabman那里找，另一个功能就去参考我的键盘修改记录

**Comment by youshupp** [comment]
是上方功能键起初不行，后来我用了Karabiner Element就可以用了
