### ISSUE TITLE
关机重启修复的部分疑问

### ISSUE THREAD

**Issue by youshupp** [ZzMark/Thinkpad-E440-Hackintosh#6]
还有一个readme里面提到过的关机问题，您说在bios里把network wake关掉就可以修复关机重启这个问题。我试了，但是没有效果，发现笔记本连接电源时依然是关机重启，但是断开电源就完全正常。您的情况是这样吗？感觉会不会和bios版本有关系，或者是还有什么具体的BIOS设定可以给我参考一下吗？

**Comment by zzmark** [comment]
我的目前发现也会有这个问题，估计TP的主板设置上有隐藏的没法调试的设置，连接电源我也有一定概率会出现这个现象，但是不是很绝对，等过阵子我去试试其他的有线网卡驱动

**Comment by myd2898129** [comment]
关机重启这个问题，在安装10.14.1后，通过黑苹果小兵的USBPorts.kext暂时驱动所有usb接口后，莫名其妙的好了，插着适配器暂时没有关机变重启现象了，至于具体原因不清楚，结果是现在关机不再重启
