### ISSUE TITLE
Installing onto E440

### ISSUE THREAD

**Issue by zakisaad** [ZzMark/Thinkpad-E440-Hackintosh#8]
Hi, the "how to use" section doesn't really explain how to use this - 

I currently just drag and drop all the files into my $EFI/CLOVER folder, and it doesn't seem to be working.

**Comment by zzmark** [comment]
Sorry to have kept you waiting.

downloaded the current version，and uncompressed it，after this you have to put these files into the EFI partition, it can be a hard disk or a usb drive

bootable partition:
```
(root)
--EFI
  |--Boot
    |--bootx64.efi
  |--clover
    |--(some folder)
    |--cloverx64.efi
    |--config.plist
```
if efi/boot/bootx64.efi is not exist , copy efi/clover/cloverx64.efi to efi/boot/bootx64.efi
